# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df3f29e5f0b9954a8af3277af850f7148745dd8d577a881300b3efc881900b8a97f9707e9a91028d202922458f777d44f2e73bd902748f5c562a9adecb546a52

test:
  secret_key_base: 6ea12d1bfa8c2b42748a9c727733ca8f9751a501345146dc49b30a7659e3ee246e9bbb59edcfdf11f9d82fc6d284f5645fb0632d50223a6cb255d606be06eb56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
